[versions]
agp = "9.2.1"
kotlin = "2.3.21"
coreKtx = "1.18.0"
junit = "4.13.2"
junitVersion = "1.3.0"
espressoCore = "3.7.0"
lifecycleRuntimeKtx = "2.10.0"
activityCompose = "1.13.0"
composeBom = "2026.05.01"
accompanist="0.37.3"
detekt = "1.23.8"
spotless = "8.5.1"
material1 = "1.11.2"
compose-calendar = "2.10.1"
wear = "1.4.0"
workManager="2.11.2"
google-services = "4.4.4"
playServicesAdsApi = "25.3.0"
firebase-bom = "34.13.0"
crashlytics = "3.0.7"
hilt = "2.59.2"
hilt-worker="1.3.0"
hilt-binder = "1.1.4"
hilt-navigations-compose = "1.3.0"
ksp = "2.3.9"
billingKtx = "9.0.0"
appcompat = "1.7.1"
wear-compose = "1.6.2"
wearToolingPreview = "1.0.0"
logcat = "0.4"
androidx-hilt-compiler = "1.3.0"
room = "2.6.1"
watchface-complications = "1.3.0"
datastoreCore = "1.2.1"
datastoreCoreVersion = "1.2.1"
glance = "1.1.1"
mockk= "1.14.9"
coroutines= "1.11.0"
core-testing= "2.2.0"
turbine = "1.2.1"
jetbrainsKotlinJvm = "2.3.21"
inapp-update = "2.1.0"
play-review = "2.0.2"
tiles = "1.6.0"
horologist = "0.7.15"
protolayout = "1.4.0"
robolectric = "4.16.1"
playServicesWearable = "20.0.1"
playServicesLocation = "21.3.0"
wearRemoteInteractions = "1.2.0"
androix-test-core = "1.7.0"
retrofit = "3.0.0"
okhttp = "5.3.2"
kotlinxSerializationJson = "1.11.0"
retrofitKotlinxSerializationConverter = "1.0.0"
splashscreen = "1.2.0"
playServicesAuth = "21.3.0"
vico = "1.15.0"

[libraries]
androidx-core-splashscreen = { group = "androidx.core", name = "core-splashscreen", version.ref = "splashscreen" }
androidx-compose-material3-window-size-class1 = { module = "androidx.compose.material3:material3-window-size-class" }
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
androidx-test-core = { group = "androidx.test", name = "core", version.ref = "androix-test-core" }
androidx-wear = { module = "androidx.wear:wear", version.ref = "wear" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
androidx-compose-ui = { group = "androidx.compose.ui", name = "ui" }
androidx-compose-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
androidx-compose-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-compose-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
androidx-compose-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
androidx-compose-ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }
androidx-compose-material = { group = "androidx.compose.material", name = "material", version.ref = "material1" }
androidx-compose-material3 = { group = "androidx.compose.material3", name = "material3" }
compose-icons-extended = { module = "androidx.compose.material:material-icons-extended" }
androidx-hilt-compiler = { group = "androidx.hilt", name = "hilt-compiler",version.ref = "androidx-hilt-compiler" }
accompanist-permissions = { group = "com.google.accompanist", name = "accompanist-permissions", version.ref = "accompanist" }
androidx-compose-calendar = { group = "com.kizitonwose.calendar", name = "compose", version.ref = "compose-calendar" }
androidx-work-runtime-ktx = { group = "androidx.work", name = "work-runtime-ktx", version.ref = "workManager" }
play-services-ads-api = { group = "com.google.android.gms", name = "play-services-ads", version.ref = "playServicesAdsApi" }
location-play-services = { group = "com.google.android.gms", name = "play-services-location", version.ref = "playServicesLocation" }
play-services-wearable = { group = "com.google.android.gms", name = "play-services-wearable", version.ref = "playServicesWearable" }
google-firebase-bom = { group = "com.google.firebase", name = "firebase-bom", version.ref = "firebase-bom" }
google-firebase-analytics = { group = "com.google.firebase", name = "firebase-analytics" }
google-firebase-crashlytics = { group = "com.google.firebase", name = "firebase-crashlytics" }
google-firebase-ia = { group = "com.google.firebase", name = "firebase-ai" }
hilt-compiler = { group = "com.google.dagger", name = "hilt-compiler", version.ref = "hilt" }
hilt-android = { group = "com.google.dagger", name = "hilt-android", version.ref = "hilt" }
hilt-binder = { group = "com.paulrybitskyi", name = "hilt-binder", version.ref = "hilt-binder" }
hilt-binder-compiler = { group = "com.paulrybitskyi", name = "hilt-binder-compiler", version.ref = "hilt-binder" }
hilt-navigation-compose = { group = "androidx.hilt", name = "hilt-navigation-compose", version.ref = "hilt-navigations-compose" }
hilt-worker = { group = "androidx.hilt", name = "hilt-work", version.ref = "hilt-worker" }
billing-ktx = { group = "com.android.billingclient", name = "billing-ktx", version.ref = "billingKtx" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
logcat = { group = "com.squareup.logcat", name = "logcat", version.ref = "logcat" }
androidx-glance-appwidget = { group = "androidx.glance", name = "glance-appwidget", version.ref = "glance" }
androidx-glance-material3 = { group = "androidx.glance", name = "glance-material3", version.ref = "glance" }
datastore-preferences-core = { group = "androidx.datastore", name = "datastore-preferences", version.ref = "datastoreCore" }
mockk = { group = "io.mockk", name = "mockk", version.ref = "mockk" }
coroutines-test = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-test", version.ref = "coroutines" }
core-testing = { group = "androidx.arch.core", name = "core-testing", version.ref = "core-testing" }
turbine = { group = "app.cash.turbine", name = "turbine", version.ref = "turbine" }
google-inapp-update = { group = "com.google.android.play", name = "app-update", version.ref = "inapp-update" }
google-inapp-update-ktx = { group = "com.google.android.play", name = "app-update-ktx", version.ref = "inapp-update" }
play-review = { group = "com.google.android.play", name = "review", version.ref = "play-review" }
play-review-ktx = { group = "com.google.android.play", name = "review-ktx", version.ref = "play-review" }
robolectric = { group = "org.robolectric", name = "robolectric", version.ref = "robolectric" }
retrofit-core = { group = "com.squareup.retrofit2", name = "retrofit", version.ref = "retrofit" }
retrofit-kotlin-serialization = { group = "com.jakewharton.retrofit", name = "retrofit2-kotlinx-serialization-converter", version.ref = "retrofitKotlinxSerializationConverter" }
okhttp-logging = { group = "com.squareup.okhttp3", name = "logging-interceptor", version.ref = "okhttp" }
kotlinx-serialization-json = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version.ref = "kotlinxSerializationJson" }
androidx-room-runtime = { group = "androidx.room", name = "room-runtime", version.ref = "room" }
androidx-room-ktx = { group = "androidx.room", name = "room-ktx", version.ref = "room" }
androidx-room-compiler = { group = "androidx.room", name = "room-compiler", version.ref = "room" }
play-services-auth = { group = "com.google.android.gms", name = "play-services-auth", version.ref = "playServicesAuth" }
vico-compose = { group = "com.patrykandpatrick.vico", name = "compose", version.ref = "vico" }
vico-compose-m3 = { group = "com.patrykandpatrick.vico", name = "compose-m3", version.ref = "vico" }
vico-core = { group = "com.patrykandpatrick.vico", name = "core", version.ref = "vico" }
# -- bibliotecas para Wear OS --
androidx-wear-material-compose = { group = "androidx.wear.compose", name = "compose-material", version.ref = "wear-compose" }
androidx-wear-material-compose3 = { group = "androidx.wear.compose", name = "compose-material3", version.ref = "wear-compose" }
androidx-wear-compose-foundation = { group = "androidx.wear.compose", name = "compose-foundation", version.ref = "wear-compose" }
androidx-wear-tooling-preview = { group = "androidx.wear.compose", name = "compose-ui-tooling", version.ref = "wear-compose" }
androidx-wear-tiles= { group = "androidx.wear.tiles", name = "tiles", version.ref = "tiles" }
androidx-wear-tiles-material = { group = "androidx.wear.tiles", name = "tiles-material", version.ref = "tiles" }
androidx-wear-tiles-proto= { group = "androidx.wear.tiles", name = "tiles-proto", version.ref = "tiles" }
androidx-wear-holoristic-tiles= { group = "com.google.android.horologist", name = "horologist-tiles", version.ref = "horologist" }
androidx-wear-protolayout= { group = "androidx.wear.protolayout", name = "protolayout", version.ref = "protolayout" }
androidx-wear-protolayout-expression= { group = "androidx.wear.protolayout", name = "protolayout-expression", version.ref = "protolayout" }
androidx-wear-protolayout-material= { group = "androidx.wear.protolayout", name = "protolayout-material", version.ref = "protolayout" }
androidx-wear-protolayout-material3= { group = "androidx.wear.protolayout", name = "protolayout-material3", version.ref = "protolayout" }
wear-tooling-preview = { group = "androidx.wear", name = "wear-tooling-preview", version.ref = "wearToolingPreview" }
androidx-watchface-complications-data-source = { group = "androidx.wear.watchface", name = "watchface-complications-data-source", version.ref = "watchface-complications" }
androidx-watchface-complications-data-source-ktx = { group = "androidx.wear.watchface", name = "watchface-complications-data-source-ktx", version.ref = "watchface-complications" }
androidx-datastore-core = { group = "androidx.datastore", name = "datastore-core", version.ref = "datastoreCoreVersion" }
androidx-wear-remote-interactions = { group = "androidx.wear", name = "wear-remote-interactions", version.ref = "wearRemoteInteractions" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
google-services = { id = "com.google.gms.google-services", version.ref = "google-services" }
spotless = { id = "com.diffplug.spotless", version.ref = "spotless" }
crashlytics = { id = "com.google.firebase.crashlytics", version.ref = "crashlytics" }
hilt-android = { id = "com.google.dagger.hilt.android", version.ref = "hilt" }
kotlin-ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
android-library = { id = "com.android.library", version.ref = "agp" }
jacoco-convention = { id = "jacoco-convention" }
jetbrains-kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "jetbrainsKotlinJvm" }
detekt = { id = "io.gitlab.arturbosch.detekt", version.ref = "detekt" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
