package digital.tonima.core.ai.usecases

import digital.tonima.core.ai.repository.AiErrorType
import digital.tonima.core.viewmodel.UiText

sealed class BriefingResult {
    /** Freshly generated by the LLM this call. */
    data class Success(val text: String) : BriefingResult()

    /** Reused from today's earlier generation — no LLM call was made. */
    data class Cached(val text: String) : BriefingResult()

    data class Error(val message: UiText, val errorType: AiErrorType) : BriefingResult()
}
