default_platform(:android)

platform :android do
  before_all do
    ENV["GOOGLE_PLAY_SERVICE_ACCOUNT_JSON_KEY"] = ENV["PLAY_STORE_SERVICE_ACCOUNT_JSON_PLAINTEXT"]
    ENV["PACKAGE_NAME"] = "digital.tonima.kairos"

    repo_root = ENV["REPO_ROOT"]
    UI.message "REPO_ROOT: #{repo_root}"
  end

  desc "Build and upload release AAB for the phone app to Google Play"
  lane :deploy_phone do |options|
    version_code = options[:phone_version_code]
    version_name = options[:version_name]

    app_signing_store_file = File.join(ENV["REPO_ROOT"], "app", "release-key.jks")
    UI.message "App signing store file: #{app_signing_store_file}"

    gradle(
      task: ":app:bundleRelease",
      properties: {
        "android.injected.version.code" => version_code,
        "android.injected.version.name" => version_name,
        "ADMOB_APP_ID" => ENV["ADMOB_APP_ID"],
        "ADMOB_BANNER_AD_UNIT_HOME" => ENV["ADMOB_BANNER_AD_UNIT_HOME"],
        "ADMOB_BANNER_AD_UNIT_ALARM_ACTIVITY" => ENV["ADMOB_BANNER_AD_UNIT_ALARM_ACTIVITY"],
        "android.injected.signing.store.file" => app_signing_store_file,
        "android.injected.signing.store.password" => ENV["ANDROID_SIGNING_KEY_PASSWORD"],
        "android.injected.signing.key.alias" => ENV["ANDROID_SIGNING_KEY_ALIAS"],
        "android.injected.signing.key.password" => ENV["ANDROID_SIGNING_KEY_ALIAS_PASSWORD"]
      }
    )

    aab_path = Dir["#{ENV["REPO_ROOT"]}/app/build/outputs/bundle/release/*.aab"].first
    UI.user_error! "Could not find release AAB for phone app in #{aab_path}" unless File.exist?(aab_path)

    supply(
      package_name: ENV["PACKAGE_NAME"],
      aab: aab_path,
      track: "internal",
      json_key_data: ENV["GOOGLE_PLAY_SERVICE_ACCOUNT_JSON_KEY"],
      version_code: version_code,
      version_name: version_name,
      skip_upload_metadata: true,
      skip_upload_screenshots: true,
      skip_upload_changelogs: false,
      timeout: 600 # App uploads can take a while (up to 10 minutes)
    )
  end

  desc "Build and upload release AAB for the Wear OS app to Google Play"
  lane :deploy_wear do |options|
    version_code = options[:wear_version_code]
    version_name = options[:version_name]

    wear_signing_store_file = File.join(ENV["REPO_ROOT"], "wear", "release-key.jks")
    UI.message "Wear signing store file: #{wear_signing_store_file}"

    gradle(
      task: ":wear:bundleRelease",
      properties: {
        "android.injected.version.code" => version_code,
        "android.injected.version.name" => version_name,
        "android.injected.signing.store.file" => wear_signing_store_file,
        "android.injected.signing.store.password" => ENV["ANDROID_SIGNING_KEY_PASSWORD"],
        "android.injected.signing.key.alias" => ENV["ANDROID_SIGNING_KEY_ALIAS"],
        "android.injected.signing.key.password" => ENV["ANDROID_SIGNING_KEY_ALIAS_PASSWORD"]
      }
    )

    aab_path = Dir["#{ENV["REPO_ROOT"]}/wear/build/outputs/bundle/release/*.aab"].first
    UI.user_error! "Could not find release AAB for wear app in #{aab_path}" unless File.exist?(aab_path)

    supply(
      package_name: ENV["PACKAGE_NAME"],
      aab: aab_path,
      track: "wear:internal",
      json_key_data: ENV["GOOGLE_PLAY_SERVICE_ACCOUNT_JSON_KEY"],
      version_code: version_code,
      version_name: version_name,
      skip_upload_metadata: true,
      skip_upload_screenshots: true,
      skip_upload_changelogs: false,
      timeout: 600 # wear uploads can take a while (up to 10 minutes)
    )
  end
end
